### ISSUE TITLE
upgrade django version

### ISSUE THREAD

**Issue by Monal5031** [NJACKWinterOfCode/cruzz#12]
django.middleware.common.CommonMiddleware in Django 1.11.x before 1.11.15 and 2.0.x before 2.0.8 has an Open Redirect.
Thus we need to upgrade it to 2.0.8 or later

**Comment by Sai-Adarsh** [comment]
![image](https://user-images.githubusercontent.com/21096774/49682932-bae62d00-fae2-11e8-9315-d7a9455101f8.png)


> Pipenv also need to be changed (2 min googling will get you how to do so) also before that check for the compatibility too, no new errors should rise :p

Pipfile.lock already has django==2.1.3, hence i'll give a PR for pipfile and requirements.txt :)
