### ISSUE TITLE
Update Installation_Setup.md

### ISSUE THREAD

**Issue by sourabhpruthi10** [NJACKWinterOfCode/cruzz#27]
setup installation instructions steps need one more additional step 
between step 4 and step 5 one should mention the following command to activate virtual environment
source venv/bin/activate

**Comment by Rutwik99** [comment]
I'll work on this.

**Comment by sourabhpruthi10** [comment]
@Rutwik99 i was waiting for mentor to get it assigned to me . @Monal5031 please assign it to me

**Comment by Monal5031** [comment]
@Rutwik99 I'm sorry due to some other engagements I couldn't assign or comment on this issue for @sourabh1031 to go for it. Please look for other issues which you might find interesting. (There are lots of easy ones, ping me if you can't find one)
